# development docker-compose.yml
services:
  server:
    image: ip-server
    build:
      context:
        .
    ports:
      - 8000:8000
  client:
    image: ip-server
    build:
      context:
        .
    entrypoint: ip-server
    command: "-c server:8000"
    depends_on:
      server:
        condition:
          service_started
    restart: unless-stopped