name: build, publish, image, and test
on: workflow_dispatch
jobs:
  cargo:
    name: build and publish cargo crate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: builds cargo package and publishes to crates.io
        run: ./ci/cargo/run.sh ${{ secrets.CARGO_TOKEN }}
  docker:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: cargo
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: builds docker image by installing cargo binary from crates.io then pushes docker image to hub.docker.com
        run: ./ci/docker/build-and-push.sh ${{ secrets.DOCKER_REGISTRY_USER }} ip-server latest ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
  test:
    name: test docker image
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test image from hub.docker.com as server and client
        run: ./ci/docker/test-server-client.sh ${{ secrest.DOCKER_REGISTRY_USER }} ip-server latest