name: docker
on: workflow_dispatch
jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and push to docker registry
        run: ls -l && ls -l ./ci && ls -l ./ci/cargo/docker && ./ci/cargo/docker/publish.sh ${{ secrets.DOCKER_REGISTRY_USER }} ${{ secrets.DOCKER_REGISTRY_PASSWORD }}