name: docker
on: workflow_dispatch
jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and push to docker registry
        run: ./ci/docker/build-and-push.sh ${{ secrets.DOCKER_REGISTRY_USER }} ip-server latest ${{ secrets.DOCKER_REGISTRY_PASSWORD }}